# Generated by Django 3.1.5 on 2021-01-31 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Время создания')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('image', models.FileField(blank=True, null=True, unique=True, upload_to='images/', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
